version: 1

update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "daily"
    # Apply default reviewer and label to created
    # pull requests
    default_reviewers:
      - "dstoianov"
#    default_labels:
#      - "dependabot"
